#!/bin/sh
ln -sf /nobackup1/stephdut/ECCO_Iter3.73daily
ln -sf /nfs/micklab002/jahn/forcing/eccov3/DARWIN_ECCO_run17
ln -sf /nfs/micklab002/jahn/forcing/eccov3/OPTICS_COEFF
ln -sf /nfs/micklab002/jahn/forcing/eccov3/eccov3
ln -sf /nfs/micklab002/jahn/forcing/eccov3/input_ecco
ln -sf /nfs/micklab005/jahn/work/kei/gitlab/setups/natgeo/run/pickup*.darwin.* .
