#!/bin/sh
module load intel/2018-01
module load impi/2018-01
module use /home/jahn/software/modulefiles
module load jahn/netcdf-fortran/4.4.5_intel-2018-01
#ln -sf /nobackup1/stephdut/ECCO_Iter3.73daily
ln -sf /home/ssharoni
ln -sf /nfs/micklab001/stephdut/ECCO_Iter3.73daily_360days
ln -sf /nfs/micklab002/jahn/forcing/eccov3/DARWIN_ECCO_run17
ln -sf /nfs/micklab002/jahn/forcing/eccov3/OPTICS_COEFF
ln -sf /nfs/micklab002/jahn/forcing/eccov3/eccov3
ln -sf /nfs/micklab002/jahn/forcing/eccov3/input_ecco
ln -sf /nfs/micklab005/jahn/work/kei/gitlab/setups/natgeo/run/pickup*.darwin.* .
#cp ../build/mitgcmuv .
#SBATCH --mail-user=ssharoni@mit.edu
#SBATCH --mail-type=BEGIN,END,FAIL  %email me when it starts/end
sbatch -p sched_mit_darwin2 -n 144 --mem=0 --wrap "mpirun -n 144 ./mitgcmuv"
#cp /nobackup1/ssharoni/gud/utils/python/MITgcmutils/scripts/gluemncbig .
#./gluemncbig -o adding_diagnostics_test_run51.nc mnc_test_*/3d.*.nc